---

- name: Install useful packages
  hosts: all
  tags: 
  - packages
  - updates
  - setup
  roles:
    - workstation_packages

- name: Install useful dotfiles
  hosts: all
  tags: 
  - setup
  roles:
    - dotfiles


- name: Install useful packages
  hosts: all
  tags: 
  - packages
  - i3wm
  roles:
    - copy_files
    - i3wm


